apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: service-weinmann
build:
  artifacts:
    - image: docker.informatik.hs-furtwangen.de/cnc-weinmann/service
      jib:
        args:
          - -Dmaven.test.skip=true
deploy:
  helm:
    releases:
      - name: service-weinmann
        chartPath: src/charts/service
        artifactOverrides:
          image: docker.informatik.hs-furtwangen.de/cnc-weinmann/service