replicaCount: 3
image: docker.informatik.hs-furtwangen.de/cnc-weinmann/service:latest
author: weinmann
port: 8080
ingressPort: 80
readinessDelay: 15
livenessDelay: 15
mongodb:
  podLabels:
    author: weinmann
  extraFlags:
    - "--wiredTigerEngineConfigString=log=(prealloc=false,file_max=20MB)"
    - "--setParameter diagnosticDataCollectionEnabled=false"
  auth:
    enabled: false
  persistence:
    size: 256Mi
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi