server:
  servlet:
    context-path: /weinmann
management:
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    tags:
      application: service-weinmann
service:
  backend: "http://localhost:8080/weinmann"
  routingKey: "weinmann"
spring:
  rabbitmq:
    port: 5672
    username: cnc
    password: cnc
    virtual-host: /cnc
    ssl:
      enabled: false