apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-weinmann
  labels:
    app: service
    author: weinmann
spec:
  endpoints:
    - interval: 30s
      path: /weinmann/actuator/prometheus
      port: web
  selector:
    matchLabels:
      app: service
      author: weinmann