apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.author }}
spec:
  rules:
    - host: kube.informatik.hs-furtwangen.de
      http:
        paths:
          - path: /{{ .Values.author }}
            pathType: Prefix
            backend:
              service:
                name: service-{{ .Values.author }}
                port:
                  number: {{ .Values.ingressPort }}