apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-{{ .Values.author }}
  labels:
    app: service
    author: {{ .Values.author }}
spec:
  endpoints:
    - interval: 30s
      path: /{{ .Values.author }}/actuator/prometheus
      port: web
  selector:
    matchLabels:
      app: service
      author: {{ .Values.author }}