apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.author }}
  labels:
    app: service
    author: {{ .Values.author }}
spec:
  ports:
    - name: web
      port: {{ .Values.ingressPort }}
      targetPort: {{ .Values.port }}
  selector:
    app: service
    author: {{ .Values.author }}